#!/usr/bin/env python

import sys
import os

from vendorize.files import mkdir_p, copy, copy_recursive
from vendorize import pypi


def main():
    requirement = sys.argv[1]
    target_directory = sys.argv[2]
    
    with pypi.download_requirement_source(requirement) as source:
        mkdir_p(target_directory)
        
        for top_level_name in source.top_level():
            module_path = os.path.join(source.path, top_level_name + ".py")
            if os.path.exists(module_path):
                copy(module_path, target_directory)
            
            package_path = os.path.join(source.path, top_level_name)
            if os.path.exists(package_path):
                target_package_directory = os.path.join(target_directory, top_level_name)
                copy_recursive(package_path, target_package_directory)


if __name__ == "__main__":
    main()
